### PR TITLE
Enhancement/skale 1528 automate ci

### PR DESCRIPTION
**Pull request by DmytroNazarenko**
Move to Github Actions

### CODE REVIEW

**Review by dmytrotkk — DISMISSED** [review]

**Comment by dmytrotkk** [comment]
great!

**Review by cstrangedk — CHANGES_REQUESTED** [review]
please fix codacy issues and codecov reporting

**Review by cstrangedk — DISMISSED** [review]
lgtm

**Review by cstrangedk — APPROVED** [review]
lgtm

**Pull request merged**
